"""
Django settings for DynamicForms project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-hbk47fadt)5jbpmu473)t-a^kwt(370e*q#tyfz5@lu(pexcq6'

SECRET_KEY = config('SECRET_KEY')


# TOGGLE CONSTANTS
USE_S3 = config('USE_S3',cast=bool,default=False)
USE_DOCKER = config('USE_DOCKER',cast=bool,default=False)
USE_EMAIL=config('USE_EMAIL',default=False)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG',cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(",")

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS').split(",")

SECURE_CROSS_ORIGIN_OPENER_POLICY = None



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'application',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DynamicForms.urls'

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS').split(",")
CORS_ALLOW_HEADERS = "*"
CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'application.templatetags.custom_tags',
                ]
        },
    },
]

WSGI_APPLICATION = 'DynamicForms.wsgi.application'


DATABASES = {
    'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': config('DATABASE_NAME'),
                'USER': config('DATABASE_USER'),
                'PASSWORD': config('DATABASE_PASSWORD'),
                'HOST': config('DATABASE_HOST'),
                'PORT': 3306,
                'OPTIONS': {
                    "init_command": "SET foreign_key_checks = 0;",
                    'init_command': "SET time_zone='+00:00'",         
                }
    }

}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIMEZONE CONFIG
TIME_ZONE = config('TIME_ZONE',default='Asia/Kolkata')
USE_I18N = True
USE_TZ = config('USE_TZ',cast=bool)


# PHONE NUMBER CONFIG
PHONENUMBER_DB_FORMAT=config('PHONENUMBER_DB_FORMAT',default='NATIONAL')
PHONENUMBER_DEFAULT_REGION=config('PHONENUMBER_DEFAULT_REGION',default='IN')


if USE_S3:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_CUSTOM_DOMAIN =  f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com' 
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'static'
    AWS_DEFAULT_ACL = None
    STATIC_URL =  'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
    STATIC_ROOT = 'static'

    STATICFILES_STORAGE = 'DynamicForms.storage_backends.StaticStorage'
    PUBLIC_MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'DynamicForms.storage_backends.PublicMediaStorage'

else:
    STATIC_URL = 'static/'
    STATIC_ROOT = 'static'

    MEDIA_URL = 'media/'
    MEDIA_ROOT = 'media'

if USE_EMAIL:
    EMAIL_HOST = config("EMAIL_HOST")
    EMAIL_HOST_USER = config("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
    EMAIL_PORT = config("EMAIL_PORT")
    EMAIL_USE_TLS=config("EMAIL_USE_TLS",cast=bool)
    EMAIL_BACKEND=config("EMAIL_BACKEND")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
